# image will be published to ghcr.io/<user>/<name>
name: oma-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
       - https://copr.fedorainfracloud.org/coprs/faramirza/fzf/repo/fedora-%OS_VERSION%/faramirza-fzf-fedora-%OS_VERSION%.repo
       - https://copr.fedorainfracloud.org/coprs/vulongm/gamescope-git/repo/fedora-%OS_VERSION%/vulongm-gamescope-git-fedora-%OS_VERSION%.repo
    install:
      # - gamescope
      # - steam
       - mangohud
       - iscsi-initiator-utils
       - kf6-kimageformats
       - fish
       - virt-manager
       - qemu-device-usb-host
       - qemu-device-usb-redirect
       - firefox
       - firefox-langpacks
       - qt-heif-image-plugin
      # - corectrl
       
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
       - mesa-va-drivers-freeworld
       - fzf
       # DX
      # - adobe-source-code-pro-fonts
      # - cascadia-code-fonts
      # - devpod
      # - flatpak-builder
      # - jetbrains-mono-fonts-all
      # - lxc
      # - powerline-fonts
      # - powertop
      # - ubuntu-family-fonts
      # - skanpage
      # - epson-inkjet-printer-escpr
      # - epson-inkjet-printer-escpr2
      # - hplip
      # - printer-driver-brlaser
      # - solaar
      # - code
      # - input-remapper
      # - rpmfusion-free-release
      # - rpmfusion-nonfree-release

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
         - org.mozilla.firefox
         - com.github.johnfactotum.Foliate
         - io.mpv.Mpv
         - org.keepassxc.KeePassXC
         - org.mozilla.Thunderbird
         - org.gnome.World.PikaBackup
         - org.kde.okular
         - org.kde.gwenview
         
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog
      # DX
      # - app/org.gnome.DejaDup/x86_64/stable
      # - app/io.github.dvlv.boxbuddyrs/x86_64/stable
      # - app/io.github.flattool.Warehouse/x86_64/stable

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

